
spring:
    datasource:
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:mysql://10.0.98.5:3306/hq_school?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
            password: root
            username: root
            driver-class-name: com.mysql.jdbc.Driver
            minimum-idle: 5
            maximum-pool-size: 20
            idle-timeout: 600000
            connection-timeout: 30000
            max-lifetime: 1800000
    rabbitmq:
        host: ocalhost
        port: 5672
        username: guest
        password: guest
configName: dev_config（修改后内容8888）

#动态刷新配置
management:
    security:
        enabled: false

















